FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish ControlGateway.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:2.1-stretch-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

# RUN useradd -ms /bin/bash moduleuser
# USER moduleuser
ENV TZ Asia/Kolkata
ENTRYPOINT ["dotnet", "ControlGateway.dll"]